# Scala setup.
language: scala
scala:
  - "2.12.8"
jdk:
  - openjdk8

# Cache Maven and SBT packages so we don't need to keep reinstalling them.
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sbt

# Make sure that Scalafmt and Scalafix are happy with the code.
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
  - sbt ++$TRAVIS_SCALA_VERSION scalafixCheckAll
