import java.io.File
import java.time.ZonedDateTime
import java.util.Calendar

import com.typesafe.scalalogging.LazyLogging
import com.github.tototoshi.csv.CSVReader

/**
 * CreateSHACLFromGoogleDocs reads the Google Docs as exported to CSV sheets in an input directory
 * and produces SHACL shapes for the specified attributes.
 */

object CreateSHACLFromGoogleDocs extends App with LazyLogging {
  val inputDir = new File(args(0))

  // Step 1. Read Type.csv to get a list of classes.
  val entities: Seq[Map[String, String]] = CSVReader.open(new File(inputDir, "Type.csv")).allWithHeaders
  val entitiesById: Map[String, Seq[Map[String, String]]] = entities.groupBy(_.getOrElse("id", "(unknown)"))

  // Step 2. Read Attribute.csv to get a list of attributes.
  val attributes: Seq[Map[String, String]] = CSVReader.open(new File(inputDir, "Attribute.csv")).allWithHeaders
  val attributesById: Map[String, Seq[Map[String, String]]] = attributes.groupBy(_.getOrElse("id", "(unknown)"))

  // Step 3. If a Type has a parentType, then it should have all the attributes of the parentType
  // as well.
  def getAllAttributes(entityId: String): Seq[Map[String, String]] = {
    if (entityId == "") return Seq()
    val attrs: Seq[Map[String, String]] = attributes.filter(attr => attr.contains("entityId") && attr("entityId") == entityId)
    val parentAttrs: Seq[Map[String, String]] = entitiesById.get(entityId).map(_.flatMap { entity: Map[String, String] =>
      entity.get("parentType").map(getAllAttributes(_)).getOrElse(Seq())
    }).getOrElse(Seq())
    parentAttrs ++ attrs
  }

  val output = System.out
  output.println(
    s"""@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
       |@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
       |@prefix sh: <http://www.w3.org/ns/shacl#> .
       |@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
       |@prefix obo: <http://purl.obolibrary.org/obo/> .
       |
       |@prefix prov: <http://www.w3.org/ns/prov#> .
       |@prefix dc: <http://purl.org/dc/elements/1.1/> .
       |@prefix SEPIO: <http://purl.obolibrary.org/obo/SEPIO_> .
       |@prefix GENO: <http://purl.obolibrary.org/obo/GENO_> .
       |
       |@prefix cgshapes: <http://dataexchange.clinicalgenome.org/interpretation/shacl/shapes/> .
       |
       |# This SHACL file was autogenerated at ${ZonedDateTime.now()}.
       |
       |""".stripMargin)

  val allAttributes = entitiesById.keys.toSeq.sorted.foreach(entityId => {
    val attributesAsString = getAllAttributes(entityId).map(attr =>
      s"""
         |  sh:property [
         |    sh:name "${attr("name")}" ;
         |  ]""".stripMargin
    ).mkString("")

    entitiesById(entityId).map(entity => {
      s"""cgshapes:${entity("name")} a sh:NodeShape ;
         |  ${if (entity.contains("iri")) s"""sh:targetClass ${entity("iri")} ; # ${entity.getOrElse("iri-label", "unlabelled")}"""}
         |  ${attributesAsString}
         |.""".stripMargin
    }).foreach(output.println(_))
  })
}
